# 100 Numpy Exercises

[Source]([Source](https://www.w3resource.com/python-exercises/numpy/index.php))

In [3]:
import numpy as np
import matplotlib.pyplot as plt


nonZero = np.array([1,2,3,4,5,6,7,8,9,]) # non-zero
withOneZero =np.array([0,1,2,3,4,5,6,7,8,9,]) 
allZero = np.array([0,0,0,0,0,0,0,0])
infiniteArray = np.array([np.inf])
nanArray = np.array([np.nan])
nanWithInfinity = np.array([np.nan, np.inf])
numbersNanWithInfinity = np.array([1,2,2,3,np.nan, np.inf,7,8,])
negativeInfinity = np.array([8,-np.inf,-7])
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])

In [ ]:
# Q. Import and Build Info

print(np.__version__,"\n",np.show_config())

In [ ]:
# How to get Help for any function
print(np.info(np.add)) # for add function

In [ ]:
# How to test if any of the element in the array are zero
# all function check if the element in the array are zero even if one is zeo it will return false otherwise true


n = np.array([0,0,0,0,1])
print(np.all(n))
# if even one array is non- zero is return true
print(np.any(n))


In [ ]:
# Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).

## return true for the number which have infinite number
print(np.isfinite(numbersNanWithInfinity))
# same goes for the nan number
print(np.isnan(nanArray))


In [ ]:
# Check if the any numbers inside the array are positive infinity otr negative infinity
print(np.isposinf(nanWithInfinity))
print(np.isneginf(negativeInfinity))

In [ ]:
# Complex Number or real Number or Scalar

print(np.iscomplex(nonZero))
print(np.isreal(withOneZero))
print(np.isscalar(nonZero))

In [ ]:
# Two Equal array with and without tolerance (absolute and relative)
print(np.allclose([1,2,3,4,5], [1,2,3,4,5]))
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True)) 

In [ ]:
# Element wise equality (greater or equal or less)

# first array in greater than second array based on each element
print(np.greater([1,2,3,4], [0,1,2,3]))

print(np.greater_equal([-1,2,3,4,5], [0,1,2,3,4]))

print(np.less([1,2,3,4],[0,1,2,3]))

print(np.less_equal([1,2,3],[0,1,2]))

print(np.equal([1,2,3,4,5],[1,2,3,4,5]))


In [ ]:
siz = np.array([1, 7, 13, 105])
print(siz.size * siz.itemsize, "Bytes")   

In [ ]:
# Create an array of 10 zeros 10 ones and 10 fives

ze = np.zeros(10,dtype=int)
on = np.ones(10, dtype=int)
fv = np.ones(10, dtype=int)* 5
print(ze,"\n",on,"\n",fv)

In [ ]:
# Write a NumPy program to create an array of integers from 30 to 70.
print(np.arange(30, 71,dtype=int))


In [ ]:
# Write a NumPy program to create an array of all even integers from 30 to 70.
print(np.arange(30,71,2, dtype=int))

In [ ]:
# Write a NumPy program to create a 3x3 identity matrix.

print(np.identity(3, dtype=int))

In [ ]:
# Write a NumPy program to generate a random number between 0 and 1.

print(np.random.normal(0,1,1))

In [ ]:
# Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

print(np.random.standard_normal(15))

In [ ]:
# Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

vec = np.arange(15,56,dtype=int)
print(vec[1:-1])

In [ ]:
# Write a NumPy program to create a 3X4 array and iterate over it.
from numpy import nditer


threeByFour = np.arange(10,22).reshape(3,4)
print(threeByFour)
for x in nditer(threeByFour):
    print("Each Element: ",x)

In [ ]:
# Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.
print(np.linspace(10,49,10,dtype=int))

In [ ]:
# Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.
signVec =np.arange(21,dtype=int)
signVec[(signVec>=9) & (signVec <=15)] *= -1
print(signVec)

In [ ]:
# Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

print(np.random.randint(0,10,5))
print(np.arange(0,20, 4))

In [ ]:
# Write a NumPy program to multiply the values of two given vectors.

print(np.array([3,2,6,8,8]) *  np.random.randint(0, 11, 5))

In [ ]:
# Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.
print(np.arange(10,22).reshape(3,4))

In [ ]:
# Write a NumPy program to find the number of rows and columns in a given matrix.
print(np.arange(10,22).reshape(3,4).shape)

In [ ]:
# Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0.

print(np.identity(3, dtype=int))
print(np.eye(3,dtype=int))

In [ ]:
# Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

tenByTen =np.ones((10,10),dtype=int) 
# print(tenByTen)
tenByTen[1:-1, 1:-1]=0
print(tenByTen)


In [ ]:
# Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.
print(np.diag([1,2,3,4,5]))

In [ ]:
# Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.
fourByFour = np.zeros((4,4),dtype=int)
fourByFour[::2, 1::2]=1
fourByFour[1::2,::2]=1
print(fourByFour)

In [ ]:
# Write a NumPy program to create a 3x3x3 array filled with arbitrary values.
print(np.random.random((3, 3, 3)))

In [ ]:
# Write a NumPy program to compute the sum of all elements, the sum of each column and the sum of each row in a given array.
#sum have properties axis=0 for columns and axis=1 for rows
print(np.random.random(4).sum())

print(np.arange(10,22).reshape(3,4).sum(axis=0))
print(np.arange(10,22).reshape(3,4).sum(axis=1))


In [ ]:
# Write a NumPy program to compute the inner product of two given vectors.
a = np.array([4,5])
b = np.array([5,4])

# Dot Product or Inner Product or Multiplication = same names
print(np.dot(a,b))

In [ ]:
#Write a NumPy program to add a vector to each row of a given matrix.
m = np.arange(10,22).reshape(3,4)
print(m)
v = np.array([1,2,3,4])
e = np.empty_like(m)
for i in range(3):
    print(e[i,:])
    print(m[i,:])
    e[i,:] = m[i,:]+v
print(e)

In [ ]:
# Write a NumPy program to save a given array to a binary file .
np.array([1,2,3,4,5,6,7,8,9])
# np.save("array", a)
# np.load("array.npy")

In [ ]:
# Write a NumPy program to save a given array to a binary file.
# np.savez("temp", np.arange(1,11), np.array([1,2,3,4,5]))
# with np.load("temp.npz") as data:
#     print(data)

In [145]:
# Write a NumPy program to save a given array to a text file and load it.
# np.savetxt("temp.txt", np.arange(11, dtype=int))
# print(np.loadtxt("temp.txt"))

In [ ]:
# Write a NumPy program to convert a given array into bytes, and load it as an array.
b = np.arange(10).tobytes()
print(b)
print(np.frombuffer(b, dtype=int))


In [ ]:
# Write a NumPy program to convert a given list into an array, then again convert it into a list. Check initial list and final list are equal or not.
li = np.arange(11).tolist()
print(li)
toArr =np.array(li)
print(toArr)

print(li==toArr)

In [ ]:
# Write a NumPy program to compute the x and y coordinates for points on a sine curve and plot the points using matplotlib.
xCords = np.arange(0,11, 1)
yCords = np.cos(xCords)
plt.plot(xCords, yCords)
plt.show()

In [ ]:
# Write a NumPy program to convert numpy dtypes to native Python types


print(type(np.float32(0)))
print(type(np.float32(1).item()))


In [ ]:
# Write a NumPy program to add elements to a matrix. If an element in the matrix is 0, we will not add the element below this element.
def sumOfMatrixElements(m)->  int:
    # Converting the input matrix 'm' into a NumPy array 'arr'
    arr = np.array(m)
    # Initializing a variable 'element_sum' to store the sum of matrix elements
    total:int = 0  
    
    # Looping through rows of the array
    for rows in range(len(arr)):
        # Looping through columns of the array
        for columns in range(len(arr[rows])):
            # Checking if the element is 0 and the row index is less than the last row
            if arr[rows][columns] == 0 and rows < len(arr)-1:
                # Assigning 0 to the element in the next row at the same column index
                arr[rows+1][columns] = 0  
            
            # Adding the current element to the total sum
            total += arr[rows][columns]  
    
    # Returning the sum of matrix elements
    return total
m = [[1, 1, 0, 2],
     [0, 3, 0, 3],
     [1, 0, 4, 4]]
print(sumOfMatrixElements(m))

In [ ]:
# Write a NumPy program to find missing data in a given array.



def findElement(number:int, matrix:np.array)->bool:
    arr = np.array(matrix)
    for rows in range(len(arr)):
        for columns in range(len(arr[rows])):
            if np.isnan(number) and np.isnan(arr[rows][columns]):
                return True
            elif  number == arr[rows][columns]:
                return True
    return False
m = [[1, 1, 0, 2],
     [np.nan, 3, 0, 3],
     [1, 0, 4, 4]]
print(findElement(np.nan, m))

In [ ]:
# Write a NumPy program to check whether two arrays are equal (element wise) or not.
# def isEqual(matrixOne:np.array, matrixTwo:np.array)->bool:
#     arrOne= np.array(matrixOne)
#     arrTwo = np.array(matrixTwo)
#     if arrOne.shape != arrTwo.shape:
#         return False
#     for rows in range(arrOne.shape[0]):
#         for column in range(arrOne.shape[1]):
#             if np.isnan(arrOne[rows][column])and np.isnan(arrTwo[rows][column]):
#                 continue
#             if arrOne[rows][column] != arrTwo[column]:
#                 return False
#     return True


m = [[1, 1, 0, 3],
     [0, 3, 0, 3],
     [1, 0, 4, 4]]
n = [[1, 1, 0, 3],
     [0, 3, 0, 3],
     [1, 0, 4, 4]]
print(np.equal(m,n))

In [ ]:
# Write a NumPy program to create a one-dimensional array of single, two and three-digit numbers.

print(np.arange(0,10)) # One digit
print(np.arange(10,100)) # Two Digit
print(np.arange(100,1000))  # Three Digit

In [ ]:

# Write a NumPy program to create a two-dimensional array of a specified format.
print(np.arange(1,151).reshape(10,15))

In [ ]:
# Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select random numbers from a uniform distribution between 0 and 1.
np.random.seed(10)
print(np.random.rand(40))

In [ ]:
# Write a NumPy program to create a two-dimensional array with shape (8,5) of random numbers. Select random numbers from a normal distribution (200,7).
np.random.seed(20)
print(np.cbrt(7)*np.random.randn(10,4)+200)

In [ ]:
# Write a NumPy program to generate a uniform, non-uniform random sample from a given 1-D array with and without replacement.
print(np.random.choice(7,5))
print(np.random.choice(7,5, replace=False))
print(np.random.choice(7, 5, p=[0.1, 0.2, 0, 0.2, 0.4, 0, 0.1]))
print(np.random.choice(7, 5, replace=False, p=[0.1, 0.2, 0, 0.2, 0.4, 0, 0.1]))

In [ ]:
# Write a NumPy program to create a 4x4 array with random values. Create an array from the said array swapping first and last rows.

m = np.array([[0,0,0,0],[1,1,1,1],[2,2,2,2],[3,3,3,3]])
m[[0,-1],:] = m[[-1,0],:]
print(m)

In [ ]:
# Write a NumPy program to create a new array of given shape (5,6) and type, filled with zeros.
print(np.arange(0,30).reshape(5,6)*0)
print(np.zeros(shape=(5,6),dtype=int))

In [ ]:
# Write a NumPy program to sort a given array by row and column in ascending order.
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])

print(np.sort(nums,axis=0))


In [ ]:
# Write a NumPy program to extract all numbers from a given array less and greater than a specified number.

def extract(arr, number):
    print(arr[arr > number])
    print(arr[arr < number])
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])

extract(nums, 5)

In [ ]:
# Write a NumPy program to replace all numbers in a given array equal, less and greater than a given number.

def replaceAll(arr, number, newNumber):
    print(np.where(arr < number, newNumber, arr))
    print(np.where(arr == number, newNumber,arr))

arr = np.arange(0,10)
replaceAll(arr,0,5)

In [ ]:
# Write a NumPy program to create an array of equal shape and data type for a given array.
print(np.zeros(shape=3,dtype=int))

In [87]:
# Write a NumPy program to create a three-dimensional array with the shape (3,5,4) and set it to a variable.
np.arange(60).reshape(3,5,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [95]:
# Write a NumPy program to create a 4x4 array. Create an array from said array by swapping first and last, second and third columns.

arr = np.arange(16).reshape(4,4)
arr = arr[:,::-1]
print(arr)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [97]:
# Write a NumPy program to swap rows and columns of a given array in reverse order
nums = np.array([[[1, 2, 3, 4],
               [0, 1, 3, 4],
               [90, 91, 93, 94],
               [5, 0, 3, 2]]])
nums =nums[::-1,::-1]
print(nums)

[[[ 5  0  3  2]
  [90 91 93 94]
  [ 0  1  3  4]
  [ 1  2  3  4]]]


In [101]:
# Write a NumPy program to multiply two given arrays of the same size element-by-element.
n= np.array([[[1, 2, 3, 4],
               [0, 1, 3, 4],
               [90, 91, 93, 94],
               [5, 0, 3, 2]]])
m =  np.array([[[1, 2, 3, 4],
               [0, 1, 3, 4],
               [90, 6, 93, 94],
               [5, 0, 3, 2]]])
print(np.multiply(m,n))

[[[   1    4    9   16]
  [   0    1    9   16]
  [8100  546 8649 8836]
  [  25    0    9    4]]]
